#!/bin/bash

[ "${DEBUG}" == "yes" ] && set -x

function print_log() {
  local date_time=`date '+%Y-%m-%dT%H:%M:%S.%N%:z'`
  local host_name=`hostname`
  local process_name="runit_bootstrap"
  local pid=$$
  local message=$1
  
  echo "${date_time} ${host_name} ${process_name}[${pid}]: ${message}"
}

function add_config_value() {
  local key=${1}
  local value=${2}
  local config_file=${3:-/etc/postfix/main.cf}
  [ "${key}" == "" ] && echo "ERROR: No key set !!" && exit 1
  [ "${value}" == "" ] && echo "ERROR: No value set !!" && exit 1
  local property_hits=`grep -v '^#' $config_file | grep -c $key`
  if [ $property_hits -eq 0 ]
  then
	print_log 'Adding configuration option "'${key}'" with value: "'${value}'"'
	echo "${key} = ${value}" >> $config_file
  else
	print_log 'Replacing configuration option "'${key}'" with value: "'${value}'"'
    sed -i -e 's/^${key}.*/${key} = ${value}/g' $config_file
  fi
}

[ -z "${SMTP_SERVER}" ] && echo "SMTP_SERVER is not set" && exit 1
[ -z "${SMTP_USERNAME}" ] && echo "SMTP_USERNAME is not set" && exit 1
[ -z "${SMTP_PASSWORD}" ] && echo "SMTP_PASSWORD is not set" && exit 1
[ -z "${SERVER_HOSTNAME}" ] && echo "SERVER_HOSTNAME is not set" && exit 1

SMTP_PORT="${SMTP_PORT-25}"
RECIPIENT_LIMIT="${RECIPIENT_LIMIT-1000}"

# Set needed config options
add_config_value "inet_protocols" "ipv4"
add_config_value "inet_interfaces" "all"
add_config_value "mynetworks" "0.0.0.0/0"
add_config_value "myhostname" ${SERVER_HOSTNAME}
add_config_value "mydestination" '$myhostname'
add_config_value "myorigin" '$myhostname'
add_config_value "relayhost" "[${SMTP_SERVER}]:${SMTP_PORT}"
add_config_value "smtpd_recipient_limit" ${RECIPIENT_LIMIT}
add_config_value "smtp_use_tls" "yes"
add_config_value "smtp_sasl_auth_enable" "yes"
add_config_value "smtp_sasl_password_maps" "hash:/etc/postfix/sasl_passwd"
add_config_value "smtp_sasl_security_options" "noanonymous"

# Create sasl_passwd file with auth credentials
if [ ! -f /etc/postfix/sasl_passwd ]; then
  grep -q "${SMTP_SERVER}" /etc/postfix/sasl_passwd  > /dev/null 2>&1
  if [ $? -gt 0 ]; then
    print_log "Adding SASL authentication configuration."
    echo "[${SMTP_SERVER}]:${SMTP_PORT} ${SMTP_USERNAME}:${SMTP_PASSWORD}" >> /etc/postfix/sasl_passwd
    postmap /etc/postfix/sasl_passwd
  fi
fi

#Set header tag  
if [ ! -z "${SMTP_HEADER_TAG}" ]; then
  postconf -e "header_checks = regexp:/etc/postfix/header_tag"
  echo -e "/^MIME-Version:/i PREPEND RelayTag: $SMTP_HEADER_TAG\n/^Content-Transfer-Encoding:/i PREPEND RelayTag: $SMTP_HEADER_TAG" > /etc/postfix/header_tag
  print_log "Setting configuration option SMTP_HEADER_TAG with value: ${SMTP_HEADER_TAG}"
fi

# Generate aliases.db
newaliases

exec /sbin/runsvdir /etc/service
