#!/bin/sh

[ "${DEBUG}" == "yes" ] && set -x

function print_log() {
  local date_time=`date '+%Y-%m-%dT%H:%M:%S.%N%:z'`
  local host_name=`hostname`
  local process_name="runit_bootstrap"
  local pid=$$
  local message=$1
  
  echo "${date_time} ${host_name} ${process_name}[${pid}]: ${message}"
}

function add_config_value() {
  local key=${1}
  local value=${2}
  local config_file=${3:-/etc/postfix/main.cf}
  [ "${key}" == "" ] && echo "ERROR: No key set !!" && exit 1
  [ "${value}" == "" ] && echo "ERROR: No value set !!" && exit 1
  local property_hits=`grep -v '^#' $config_file | grep -c $key`
  if [ $property_hits -eq 0 ]
  then
	print_log 'Adding configuration option "'${key}'" with value: "'${value}'"'
	echo "${key} = ${value}" >> $config_file
  else
	print_log 'Replacing configuration option "'${key}'" with value: "'${value}'"'
    sed -i -e 's/^${key}.*/${key} = ${value}/g' $config_file
  fi
}

# Required configuration variables
[ -z "${SMTP_SERVER}" ] && echo "SMTP_SERVER is not set" && exit 1
[ -z "${SERVER_HOSTNAME}" ] && echo "SERVER_HOSTNAME is not set" && exit 1

# Default configuration variables that can be overwritten
SMTP_PORT="${SMTP_PORT-25}"
RECIPIENT_LIMIT="${RECIPIENT_LIMIT-1000}"

# Set needed config options in main.cf
add_config_value "inet_protocols" "ipv4"
add_config_value "inet_interfaces" "all"
add_config_value "mynetworks" "0.0.0.0/0"
add_config_value "myhostname" ${SERVER_HOSTNAME}
add_config_value "mydestination" '$myhostname'
add_config_value "myorigin" '$myhostname'
add_config_value "relayhost" "[${SMTP_SERVER}]:${SMTP_PORT}"
add_config_value "smtpd_recipient_limit" ${RECIPIENT_LIMIT}
add_config_value "smtp_use_tls" "yes"

# Optional: when SMTP_USERNAME and SMTP_PASSWORD are provided, create a sasl_passwd file and add it to the Postfix configuration
if [ -n "${SMTP_USERNAME}" -a -n "${SMTP_PASSWORD}" ]
then
  if [ ! -f /etc/postfix/sasl_passwd ]; then
    grep -q "${SMTP_SERVER}" /etc/postfix/sasl_passwd  > /dev/null 2>&1
    if [ $? -gt 0 ]; then
      print_log "Adding SASL authentication configuration."
      echo "[${SMTP_SERVER}]:${SMTP_PORT} ${SMTP_USERNAME}:${SMTP_PASSWORD}" >> /etc/postfix/sasl_passwd
      postmap /etc/postfix/sasl_passwd
    fi
  fi

  add_config_value "smtp_sasl_auth_enable" "yes"
  add_config_value "smtp_sasl_password_maps" "hash:/etc/postfix/sasl_passwd"
  add_config_value "smtp_sasl_security_options" "noanonymous"
fi

# Optional: set header tag
if [ ! -z "${SMTP_HEADER_TAG}" ]; then
  postconf -e "header_checks = regexp:/etc/postfix/header_tag"
  echo -e "/^MIME-Version:/i PREPEND RelayTag: $SMTP_HEADER_TAG\n/^Content-Transfer-Encoding:/i PREPEND RelayTag: $SMTP_HEADER_TAG" > /etc/postfix/header_tag
  print_log "Setting configuration option SMTP_HEADER_TAG with value: ${SMTP_HEADER_TAG}"
fi

# Optional: rewrite outgoing domain in from-addresses
if [ ! -z "${REWRITE_DOMAIN}" ]; then
  echo -e '/^(.*@).*$/     ${1}'${REWRITE_DOMAIN} > /etc/postfix/sender_canonical
  add_config_value "sender_canonical_maps" "regexp:/etc/postfix/sender_canonical"
  print_log "Setting configuration option REWRITE_DOMAIN with value: ${REWRITE_DOMAIN}"
fi

# Optional: rewrite From-headers
if [ ! -z "${REWRITE_HEADERS}" ]; then
  echo -e "${REWRITE_HEADERS}" > /etc/postfix/header_checks
  add_config_value "smtp_header_checks" "regexp:/etc/postfix/header_checks"
  print_log "Setting configuration option REWRITE_HEADERS with value: ${REWRITE_HEADERS}"
fi

# Optional: if a script is set in variable ADDITIONAL_CONFIG, source and execute it
if [ ! -z "${ADDITIONAL_CONFIG}" -a -s "${ADDITIONAL_CONFIG}" ]; then
  . "${ADDITIONAL_CONFIG}"
fi

# Generate aliases.db
newaliases

# Start postfix
exec /sbin/runsvdir /etc/service
